<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Remove_inventory_item_img</name>
   <tag></tag>
   <elementGuidId>3297de97-305a-476f-b382-b66b32d3630e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_2_img_link']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_2_img_link > img.inventory_item_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2d88997-c614-43c1-b856-bb54a6f1e5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Onesie</value>
      <webElementGuid>8a5735a2-06f7-477a-a6c1-e7fdde7080bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_img</value>
      <webElementGuid>9c2ab5cb-b2dc-4dc6-8586-af6803c3db1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nguyen-tri-nhan.github.io/static/media/red-onesie-1200x1500.2ec615b2.jpg</value>
      <webElementGuid>46503b75-398a-4c38-93b0-cd84fb5b9cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_2_img_link&quot;)/img[@class=&quot;inventory_item_img&quot;]</value>
      <webElementGuid>d0aa517d-e5d2-4632-af27-031e1be18907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='item_2_img_link']/img</value>
      <webElementGuid>1b75f2d0-fdfa-4ee7-8d4e-e6419a5ccb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Onesie']</value>
      <webElementGuid>0fc98419-3098-4e7d-866b-25f21263a8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a/img</value>
      <webElementGuid>38e00dd7-28ac-4aaa-803f-98b468798cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Onesie' and @src = 'https://nguyen-tri-nhan.github.io/static/media/red-onesie-1200x1500.2ec615b2.jpg']</value>
      <webElementGuid>5e16c95a-ed16-48da-8fc1-0575bedd5d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
